### ISSUE TITLE
feature request: I love Essential complexity

### ISSUE THREAD

**Issue by sonatard** [nakabonne/nestif#6]
Following flowchart is same complexity, but  right one dose not have problem. It's clean code.

<img width="722" alt="complexity" src="https://user-images.githubusercontent.com/1586910/80171978-bb735b00-8626-11ea-8bff-ac96f98d672d.png">

Essential Complexity creates structures that convolute simple conditional branching structures, such as the following
<img width="717" alt="スクリーンショット 2020-04-24 12 29 19" src="https://user-images.githubusercontent.com/1586910/80172184-4e13fa00-8627-11ea-936c-68d0685e861b.png">

<img width="403" alt="スクリーンショット 2020-04-24 12 29 27" src="https://user-images.githubusercontent.com/1586910/80172189-53714480-8627-11ea-83cd-9cceac7296eb.png">

<img width="399" alt="スクリーンショット 2020-04-24 12 29 34" src="https://user-images.githubusercontent.com/1586910/80172198-5704cb80-8627-11ea-8798-e74380770955.png">

<img width="401" alt="スクリーンショット 2020-04-24 12 29 45" src="https://user-images.githubusercontent.com/1586910/80172211-5cfaac80-8627-11ea-820c-3ded72a9049e.png">

### Reference
- https://stackoverflow.com/questions/13306644/what-is-the-difference-between-cyclomatic-complexity-and-essential-cyclomatic-co
- Japanese http://understand-jp.blogspot.com/2012/09/blog-post_5.html

**Comment by ernado** [comment]
I was slightly surprised today trying to use `nestif` on one of my projects.

Seems like current approach works like that:
```go
if condition1 { // total: 4
    if condition2 { // +1
    }
    if condition3 { // +1
    }
    if condition4 { // +1
    }
}
```

Real world example:

https://github.com/gortc/turnc/blob/78f7d0d4df3287d1739a11154d6e17ebdb38748d/cmd/turn-client/client.go#L35-L64

```
cmd/turn-client/client.go:35:2: `if flag.Arg(0) == "peer"` is deeply nested (complexity: 5) (nestif)
        if flag.Arg(0) == "peer" {
        ^
```

**Comment by nakabonne** [comment]
@sonatard Thank you for your suggestions. As you mentioned, I also think Essential Cyclomatic Complexity is a good way to measure the overall complexity of the code.
However, nestif does focus on if statements, so I'd say measurement as simple as Cognitive Complexity would be appropriate.

**Comment by nakabonne** [comment]
@ernado Top-level if statements don't add up for the sake of calculation simplicity. The score for the following code would be 3:
```go
if condition1 { // total: 3
    if condition2 { // +1
    }
    if condition3 { // +1
    }
    if condition4 { // +1
    }
}
```

**Comment by sonatard** [comment]
Got it. Thank you for creating a very good tool !!
