### ISSUE TITLE
Inaccurate message wrt nesting vs complexity

### ISSUE THREAD

**Issue by scop** [nakabonne/nestif#8]
```
	if x > 1 {
		if x > 2 {
		} else if x > 3 {
		} else if x > 4 {
		}
	}
```

`nestif --min 3 main.go` gives for that:
```
main.go:8:2: `if x > 1` is deeply nested (complexity: 3)
```

I think the message is inaccurate -- that particular `if` is not _deeply nested_ above the threshold (max nesting level is 2 there), but just its complexity is above it. Would be better to rephrase the message in cases like these, for example "... has complex contents (complexity: 3)" or something.

**Comment by nakabonne** [comment]
For sure. It's nice to have the word "complex" in the message. Then how about `... is complex nested inside itself` or `... has complex nested blocks`?

**Comment by scop** [comment]
> `... has complex nested blocks`?

I think this one is easily the best one we've seen yet, certainly good enough for me :+1:

**Comment by nakabonne** [comment]
Alright. I'm going to address it when I have time, or it would be great if you could open a PR ;)

**Comment by scop** [comment]
Sure, opened PR #9.
